/**************************************************************/
/* Automatically generated by './mkconfig.sh'.  Do note edit! */
/**************************************************************/
#define YALS_OS "Linux kathleen-login-1 5.14.0-362.13.1.el9_3.x86_64 x86_64"
#define YALS_COMPILED "Thu  8 Feb 23:45:18 CET 2024"
#define YALS_RELEASED "Fr 1. Mär 05:17:48 CET 2019"
#define YALS_VERSION "03v"
#define YALS_ID "b1316746d40f72f147cde3f4ec54fadbe0730427"
